replicaCount: 1

image:
  repository: "${DOCKER_HUB_USERNAME}/payment-service"
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  nodePort: 30003

containerPort: 8005

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
