apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}          # cluster-internal port
      targetPort: {{ .Values.containerPort }}   # actual app (container) port
      nodePort: {{ .Values.service.nodePort }}  # external (Minikube) port
