name: CI - Build and Push Payment Service Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Enable QEMU to support multi-architecture builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Enable Docker Buildx (required for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub using GitHub Secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Build and push a multi-architecture image
      - name: Build and push multi-arch Docker image
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: |
          IMAGE_NAME=${DOCKER_HUB_USERNAME}/payment-service:latest
          echo "Building and pushing multi-arch image: $IMAGE_NAME"
          
          # Build and push for both amd64 and arm64 architectures
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t $IMAGE_NAME \
            --push .
